/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package at.mic.superset.swagger.client;

import at.mic.superset.swagger.ApiException;
import at.mic.superset.swagger.client.model.GetItemSchema;
import at.mic.superset.swagger.client.model.GetListSchema;
import at.mic.superset.swagger.client.model.InlineResponse20016;
import at.mic.superset.swagger.client.model.InlineResponse20017;
import at.mic.superset.swagger.client.model.InlineResponse2013;
import at.mic.superset.swagger.client.model.InlineResponse400;
import at.mic.superset.swagger.client.model.LogRestApiPost;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for LogRestApiApi
 */
@Ignore
public class LogRestApiApiTest {

    private final LogRestApiApi api = new LogRestApiApi();

    /**
     * 
     *
     * Get a list of models
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void logGetTest() throws ApiException {
        GetListSchema q = null;
        InlineResponse20016 response = api.logGet(q);

        // TODO: test validations
    }
    /**
     * 
     *
     * Get an item model
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void logPkGetTest() throws ApiException {
        Integer pk = null;
        GetItemSchema q = null;
        InlineResponse20017 response = api.logPkGet(pk, q);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void logPostTest() throws ApiException {
        LogRestApiPost body = null;
        InlineResponse2013 response = api.logPost(body);

        // TODO: test validations
    }
}
