/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package at.mic.superset.swagger.client;

import at.mic.superset.swagger.ApiException;
import at.mic.superset.swagger.client.model.InlineResponse20018;
import at.mic.superset.swagger.client.model.InlineResponse400;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MenuApi
 */
@Ignore
public class MenuApiTest {

    private final MenuApi api = new MenuApi();

    /**
     * 
     *
     * Get the menu data structure. Returns a forest like structure with the menu the user has access to
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void menuGetTest() throws ApiException {
        InlineResponse20018 response = api.menuGet();

        // TODO: test validations
    }
}
