/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package at.mic.superset.swagger.client;

import at.mic.superset.swagger.ApiException;
import at.mic.superset.swagger.client.model.InlineResponse400;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OpenApiApi
 */
@Ignore
public class OpenApiApiTest {

    private final OpenApiApi api = new OpenApiApi();

    /**
     * 
     *
     * Get the OpenAPI spec for a specific API version
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void openapiVersionOpenapiGetTest() throws ApiException {
        String version = null;
        Object response = api.openapiVersionOpenapiGet(version);

        // TODO: test validations
    }
}
