/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package at.mic.superset.swagger.client;

import at.mic.superset.swagger.ApiException;
import at.mic.superset.swagger.client.model.GetItemSchema;
import at.mic.superset.swagger.client.model.GetListSchema;
import at.mic.superset.swagger.client.model.InlineResponse20019;
import at.mic.superset.swagger.client.model.InlineResponse20020;
import at.mic.superset.swagger.client.model.InlineResponse400;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for QueriesApi
 */
@Ignore
public class QueriesApiTest {

    private final QueriesApi api = new QueriesApi();

    /**
     * 
     *
     * Get a list of queries, use Rison or JSON query parameters for filtering, sorting, pagination and  for selecting specific columns and metadata.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void queryGetTest() throws ApiException {
        GetListSchema q = null;
        InlineResponse20019 response = api.queryGet(q);

        // TODO: test validations
    }
    /**
     * 
     *
     * Get query detail information.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void queryPkGetTest() throws ApiException {
        Integer pk = null;
        GetItemSchema q = null;
        InlineResponse20020 response = api.queryPkGet(pk, q);

        // TODO: test validations
    }
}
