/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package at.mic.superset.swagger.client;

import at.mic.superset.swagger.ApiException;
import at.mic.superset.swagger.client.model.Body;
import at.mic.superset.swagger.client.model.InlineResponse20021;
import at.mic.superset.swagger.client.model.InlineResponse20022;
import at.mic.superset.swagger.client.model.InlineResponse400;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SecurityApi
 */
@Ignore
public class SecurityApiTest {

    private final SecurityApi api = new SecurityApi();

    /**
     * 
     *
     * Authenticate and get a JWT access and refresh token
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void securityLoginPostTest() throws ApiException {
        Body body = null;
        InlineResponse20021 response = api.securityLoginPost(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * Use the refresh token to get a new JWT access token
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void securityRefreshPostTest() throws ApiException {
        InlineResponse20022 response = api.securityRefreshPost();

        // TODO: test validations
    }
}
