/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package at.mic.superset.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import at.mic.superset.swagger.client.model.ChartDataResponseResult;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * ChartDataResponseSchema
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-06T17:36:10.263+01:00[Europe/Vienna]")
public class ChartDataResponseSchema {
  @SerializedName("result")
  private List<ChartDataResponseResult> result = null;

  public ChartDataResponseSchema result(List<ChartDataResponseResult> result) {
    this.result = result;
    return this;
  }

  public ChartDataResponseSchema addResultItem(ChartDataResponseResult resultItem) {
    if (this.result == null) {
      this.result = new ArrayList<ChartDataResponseResult>();
    }
    this.result.add(resultItem);
    return this;
  }

   /**
   * A list of results for each corresponding query in the request.
   * @return result
  **/
  @Schema(description = "A list of results for each corresponding query in the request.")
  public List<ChartDataResponseResult> getResult() {
    return result;
  }

  public void setResult(List<ChartDataResponseResult> result) {
    this.result = result;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChartDataResponseSchema chartDataResponseSchema = (ChartDataResponseSchema) o;
    return Objects.equals(this.result, chartDataResponseSchema.result);
  }

  @Override
  public int hashCode() {
    return Objects.hash(result);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChartDataResponseSchema {\n");
    
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
