/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package at.mic.superset.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * DatasetRelatedDashboard
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-06T17:36:10.263+01:00[Europe/Vienna]")
public class DatasetRelatedDashboard {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("json_metadata")
  private Object jsonMetadata = null;

  @SerializedName("slug")
  private String slug = null;

  @SerializedName("title")
  private String title = null;

  public DatasetRelatedDashboard id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public DatasetRelatedDashboard jsonMetadata(Object jsonMetadata) {
    this.jsonMetadata = jsonMetadata;
    return this;
  }

   /**
   * Get jsonMetadata
   * @return jsonMetadata
  **/
  @Schema(description = "")
  public Object getJsonMetadata() {
    return jsonMetadata;
  }

  public void setJsonMetadata(Object jsonMetadata) {
    this.jsonMetadata = jsonMetadata;
  }

  public DatasetRelatedDashboard slug(String slug) {
    this.slug = slug;
    return this;
  }

   /**
   * Get slug
   * @return slug
  **/
  @Schema(description = "")
  public String getSlug() {
    return slug;
  }

  public void setSlug(String slug) {
    this.slug = slug;
  }

  public DatasetRelatedDashboard title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @Schema(description = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DatasetRelatedDashboard datasetRelatedDashboard = (DatasetRelatedDashboard) o;
    return Objects.equals(this.id, datasetRelatedDashboard.id) &&
        Objects.equals(this.jsonMetadata, datasetRelatedDashboard.jsonMetadata) &&
        Objects.equals(this.slug, datasetRelatedDashboard.slug) &&
        Objects.equals(this.title, datasetRelatedDashboard.title);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, jsonMetadata, slug, title);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DatasetRelatedDashboard {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    jsonMetadata: ").append(toIndentedString(jsonMetadata)).append("\n");
    sb.append("    slug: ").append(toIndentedString(slug)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
