/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package at.mic.superset.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * DatabaseRestApiGetList
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-06T17:36:10.263+01:00[Europe/Vienna]")
public class DatabaseRestApiGetList {
  @SerializedName("allow_csv_upload")
  private Boolean allowCsvUpload = null;

  @SerializedName("allow_ctas")
  private Boolean allowCtas = null;

  @SerializedName("allow_cvas")
  private Boolean allowCvas = null;

  @SerializedName("allow_dml")
  private Boolean allowDml = null;

  @SerializedName("allow_multi_schema_metadata_fetch")
  private Boolean allowMultiSchemaMetadataFetch = null;

  @SerializedName("allow_run_async")
  private Boolean allowRunAsync = null;

  @SerializedName("allows_cost_estimate")
  private Object allowsCostEstimate = null;

  @SerializedName("allows_subquery")
  private Object allowsSubquery = null;

  @SerializedName("allows_virtual_table_explore")
  private Object allowsVirtualTableExplore = null;

  @SerializedName("backend")
  private Object backend = null;

  @SerializedName("database_name")
  private String databaseName = null;

  @SerializedName("explore_database_id")
  private Object exploreDatabaseId = null;

  @SerializedName("expose_in_sqllab")
  private Boolean exposeInSqllab = null;

  @SerializedName("force_ctas_schema")
  private String forceCtasSchema = null;

  @SerializedName("function_names")
  private Object functionNames = null;

  @SerializedName("id")
  private Integer id = null;

  public DatabaseRestApiGetList allowCsvUpload(Boolean allowCsvUpload) {
    this.allowCsvUpload = allowCsvUpload;
    return this;
  }

   /**
   * Get allowCsvUpload
   * @return allowCsvUpload
  **/
  @Schema(description = "")
  public Boolean isAllowCsvUpload() {
    return allowCsvUpload;
  }

  public void setAllowCsvUpload(Boolean allowCsvUpload) {
    this.allowCsvUpload = allowCsvUpload;
  }

  public DatabaseRestApiGetList allowCtas(Boolean allowCtas) {
    this.allowCtas = allowCtas;
    return this;
  }

   /**
   * Get allowCtas
   * @return allowCtas
  **/
  @Schema(description = "")
  public Boolean isAllowCtas() {
    return allowCtas;
  }

  public void setAllowCtas(Boolean allowCtas) {
    this.allowCtas = allowCtas;
  }

  public DatabaseRestApiGetList allowCvas(Boolean allowCvas) {
    this.allowCvas = allowCvas;
    return this;
  }

   /**
   * Get allowCvas
   * @return allowCvas
  **/
  @Schema(description = "")
  public Boolean isAllowCvas() {
    return allowCvas;
  }

  public void setAllowCvas(Boolean allowCvas) {
    this.allowCvas = allowCvas;
  }

  public DatabaseRestApiGetList allowDml(Boolean allowDml) {
    this.allowDml = allowDml;
    return this;
  }

   /**
   * Get allowDml
   * @return allowDml
  **/
  @Schema(description = "")
  public Boolean isAllowDml() {
    return allowDml;
  }

  public void setAllowDml(Boolean allowDml) {
    this.allowDml = allowDml;
  }

  public DatabaseRestApiGetList allowMultiSchemaMetadataFetch(Boolean allowMultiSchemaMetadataFetch) {
    this.allowMultiSchemaMetadataFetch = allowMultiSchemaMetadataFetch;
    return this;
  }

   /**
   * Get allowMultiSchemaMetadataFetch
   * @return allowMultiSchemaMetadataFetch
  **/
  @Schema(description = "")
  public Boolean isAllowMultiSchemaMetadataFetch() {
    return allowMultiSchemaMetadataFetch;
  }

  public void setAllowMultiSchemaMetadataFetch(Boolean allowMultiSchemaMetadataFetch) {
    this.allowMultiSchemaMetadataFetch = allowMultiSchemaMetadataFetch;
  }

  public DatabaseRestApiGetList allowRunAsync(Boolean allowRunAsync) {
    this.allowRunAsync = allowRunAsync;
    return this;
  }

   /**
   * Get allowRunAsync
   * @return allowRunAsync
  **/
  @Schema(description = "")
  public Boolean isAllowRunAsync() {
    return allowRunAsync;
  }

  public void setAllowRunAsync(Boolean allowRunAsync) {
    this.allowRunAsync = allowRunAsync;
  }

   /**
   * Get allowsCostEstimate
   * @return allowsCostEstimate
  **/
  @Schema(description = "")
  public Object getAllowsCostEstimate() {
    return allowsCostEstimate;
  }

   /**
   * Get allowsSubquery
   * @return allowsSubquery
  **/
  @Schema(description = "")
  public Object getAllowsSubquery() {
    return allowsSubquery;
  }

   /**
   * Get allowsVirtualTableExplore
   * @return allowsVirtualTableExplore
  **/
  @Schema(description = "")
  public Object getAllowsVirtualTableExplore() {
    return allowsVirtualTableExplore;
  }

   /**
   * Get backend
   * @return backend
  **/
  @Schema(description = "")
  public Object getBackend() {
    return backend;
  }

  public DatabaseRestApiGetList databaseName(String databaseName) {
    this.databaseName = databaseName;
    return this;
  }

   /**
   * Get databaseName
   * @return databaseName
  **/
  @Schema(required = true, description = "")
  public String getDatabaseName() {
    return databaseName;
  }

  public void setDatabaseName(String databaseName) {
    this.databaseName = databaseName;
  }

   /**
   * Get exploreDatabaseId
   * @return exploreDatabaseId
  **/
  @Schema(description = "")
  public Object getExploreDatabaseId() {
    return exploreDatabaseId;
  }

  public DatabaseRestApiGetList exposeInSqllab(Boolean exposeInSqllab) {
    this.exposeInSqllab = exposeInSqllab;
    return this;
  }

   /**
   * Get exposeInSqllab
   * @return exposeInSqllab
  **/
  @Schema(description = "")
  public Boolean isExposeInSqllab() {
    return exposeInSqllab;
  }

  public void setExposeInSqllab(Boolean exposeInSqllab) {
    this.exposeInSqllab = exposeInSqllab;
  }

  public DatabaseRestApiGetList forceCtasSchema(String forceCtasSchema) {
    this.forceCtasSchema = forceCtasSchema;
    return this;
  }

   /**
   * Get forceCtasSchema
   * @return forceCtasSchema
  **/
  @Schema(description = "")
  public String getForceCtasSchema() {
    return forceCtasSchema;
  }

  public void setForceCtasSchema(String forceCtasSchema) {
    this.forceCtasSchema = forceCtasSchema;
  }

   /**
   * Get functionNames
   * @return functionNames
  **/
  @Schema(description = "")
  public Object getFunctionNames() {
    return functionNames;
  }

  public DatabaseRestApiGetList id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DatabaseRestApiGetList databaseRestApiGetList = (DatabaseRestApiGetList) o;
    return Objects.equals(this.allowCsvUpload, databaseRestApiGetList.allowCsvUpload) &&
        Objects.equals(this.allowCtas, databaseRestApiGetList.allowCtas) &&
        Objects.equals(this.allowCvas, databaseRestApiGetList.allowCvas) &&
        Objects.equals(this.allowDml, databaseRestApiGetList.allowDml) &&
        Objects.equals(this.allowMultiSchemaMetadataFetch, databaseRestApiGetList.allowMultiSchemaMetadataFetch) &&
        Objects.equals(this.allowRunAsync, databaseRestApiGetList.allowRunAsync) &&
        Objects.equals(this.allowsCostEstimate, databaseRestApiGetList.allowsCostEstimate) &&
        Objects.equals(this.allowsSubquery, databaseRestApiGetList.allowsSubquery) &&
        Objects.equals(this.allowsVirtualTableExplore, databaseRestApiGetList.allowsVirtualTableExplore) &&
        Objects.equals(this.backend, databaseRestApiGetList.backend) &&
        Objects.equals(this.databaseName, databaseRestApiGetList.databaseName) &&
        Objects.equals(this.exploreDatabaseId, databaseRestApiGetList.exploreDatabaseId) &&
        Objects.equals(this.exposeInSqllab, databaseRestApiGetList.exposeInSqllab) &&
        Objects.equals(this.forceCtasSchema, databaseRestApiGetList.forceCtasSchema) &&
        Objects.equals(this.functionNames, databaseRestApiGetList.functionNames) &&
        Objects.equals(this.id, databaseRestApiGetList.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allowCsvUpload, allowCtas, allowCvas, allowDml, allowMultiSchemaMetadataFetch, allowRunAsync, allowsCostEstimate, allowsSubquery, allowsVirtualTableExplore, backend, databaseName, exploreDatabaseId, exposeInSqllab, forceCtasSchema, functionNames, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DatabaseRestApiGetList {\n");
    
    sb.append("    allowCsvUpload: ").append(toIndentedString(allowCsvUpload)).append("\n");
    sb.append("    allowCtas: ").append(toIndentedString(allowCtas)).append("\n");
    sb.append("    allowCvas: ").append(toIndentedString(allowCvas)).append("\n");
    sb.append("    allowDml: ").append(toIndentedString(allowDml)).append("\n");
    sb.append("    allowMultiSchemaMetadataFetch: ").append(toIndentedString(allowMultiSchemaMetadataFetch)).append("\n");
    sb.append("    allowRunAsync: ").append(toIndentedString(allowRunAsync)).append("\n");
    sb.append("    allowsCostEstimate: ").append(toIndentedString(allowsCostEstimate)).append("\n");
    sb.append("    allowsSubquery: ").append(toIndentedString(allowsSubquery)).append("\n");
    sb.append("    allowsVirtualTableExplore: ").append(toIndentedString(allowsVirtualTableExplore)).append("\n");
    sb.append("    backend: ").append(toIndentedString(backend)).append("\n");
    sb.append("    databaseName: ").append(toIndentedString(databaseName)).append("\n");
    sb.append("    exploreDatabaseId: ").append(toIndentedString(exploreDatabaseId)).append("\n");
    sb.append("    exposeInSqllab: ").append(toIndentedString(exposeInSqllab)).append("\n");
    sb.append("    forceCtasSchema: ").append(toIndentedString(forceCtasSchema)).append("\n");
    sb.append("    functionNames: ").append(toIndentedString(functionNames)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
