/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package at.mic.superset.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import at.mic.superset.swagger.client.model.InlineResponse2001FiltersColumnName;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * InlineResponse2001Filters
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-06T17:36:10.263+01:00[Europe/Vienna]")
public class InlineResponse2001Filters {
  @SerializedName("column_name")
  private List<InlineResponse2001FiltersColumnName> columnName = null;

  public InlineResponse2001Filters columnName(List<InlineResponse2001FiltersColumnName> columnName) {
    this.columnName = columnName;
    return this;
  }

  public InlineResponse2001Filters addColumnNameItem(InlineResponse2001FiltersColumnName columnNameItem) {
    if (this.columnName == null) {
      this.columnName = new ArrayList<InlineResponse2001FiltersColumnName>();
    }
    this.columnName.add(columnNameItem);
    return this;
  }

   /**
   * Get columnName
   * @return columnName
  **/
  @Schema(description = "")
  public List<InlineResponse2001FiltersColumnName> getColumnName() {
    return columnName;
  }

  public void setColumnName(List<InlineResponse2001FiltersColumnName> columnName) {
    this.columnName = columnName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2001Filters inlineResponse2001Filters = (InlineResponse2001Filters) o;
    return Objects.equals(this.columnName, inlineResponse2001Filters.columnName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(columnName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2001Filters {\n");
    
    sb.append("    columnName: ").append(toIndentedString(columnName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
