/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package at.mic.superset.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * InlineResponse2001FiltersColumnName
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-06T17:36:10.263+01:00[Europe/Vienna]")
public class InlineResponse2001FiltersColumnName {
  @SerializedName("name")
  private String name = null;

  @SerializedName("operator")
  private String operator = null;

  public InlineResponse2001FiltersColumnName name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The filter name. Will be translated by babel
   * @return name
  **/
  @Schema(description = "The filter name. Will be translated by babel")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public InlineResponse2001FiltersColumnName operator(String operator) {
    this.operator = operator;
    return this;
  }

   /**
   * The filter operation key to use on list filters
   * @return operator
  **/
  @Schema(description = "The filter operation key to use on list filters")
  public String getOperator() {
    return operator;
  }

  public void setOperator(String operator) {
    this.operator = operator;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2001FiltersColumnName inlineResponse2001FiltersColumnName = (InlineResponse2001FiltersColumnName) o;
    return Objects.equals(this.name, inlineResponse2001FiltersColumnName.name) &&
        Objects.equals(this.operator, inlineResponse2001FiltersColumnName.operator);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, operator);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2001FiltersColumnName {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    operator: ").append(toIndentedString(operator)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
