/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package at.mic.superset.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * InlineResponse20012Columns
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-06T17:36:10.263+01:00[Europe/Vienna]")
public class InlineResponse20012Columns {
  @SerializedName("keys")
  private List<String> keys = null;

  @SerializedName("longType")
  private String longType = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("type")
  private String type = null;

  public InlineResponse20012Columns keys(List<String> keys) {
    this.keys = keys;
    return this;
  }

  public InlineResponse20012Columns addKeysItem(String keysItem) {
    if (this.keys == null) {
      this.keys = new ArrayList<String>();
    }
    this.keys.add(keysItem);
    return this;
  }

   /**
   * Get keys
   * @return keys
  **/
  @Schema(description = "")
  public List<String> getKeys() {
    return keys;
  }

  public void setKeys(List<String> keys) {
    this.keys = keys;
  }

  public InlineResponse20012Columns longType(String longType) {
    this.longType = longType;
    return this;
  }

   /**
   * Get longType
   * @return longType
  **/
  @Schema(description = "")
  public String getLongType() {
    return longType;
  }

  public void setLongType(String longType) {
    this.longType = longType;
  }

  public InlineResponse20012Columns name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public InlineResponse20012Columns type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(description = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20012Columns inlineResponse20012Columns = (InlineResponse20012Columns) o;
    return Objects.equals(this.keys, inlineResponse20012Columns.keys) &&
        Objects.equals(this.longType, inlineResponse20012Columns.longType) &&
        Objects.equals(this.name, inlineResponse20012Columns.name) &&
        Objects.equals(this.type, inlineResponse20012Columns.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(keys, longType, name, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20012Columns {\n");
    
    sb.append("    keys: ").append(toIndentedString(keys)).append("\n");
    sb.append("    longType: ").append(toIndentedString(longType)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
