/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package at.mic.superset.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import at.mic.superset.swagger.client.model.InlineResponse20012Columns;
import at.mic.superset.swagger.client.model.InlineResponse20012ForeignKeys;
import at.mic.superset.swagger.client.model.InlineResponse20012PrimaryKey;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * InlineResponse20012
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-06T17:36:10.263+01:00[Europe/Vienna]")
public class InlineResponse20012 {
  @SerializedName("columns")
  private List<InlineResponse20012Columns> columns = null;

  @SerializedName("foreignKeys")
  private List<InlineResponse20012ForeignKeys> foreignKeys = null;

  @SerializedName("indexes")
  private List<InlineResponse20012ForeignKeys> indexes = null;

  @SerializedName("primaryKey")
  private InlineResponse20012PrimaryKey primaryKey = null;

  public InlineResponse20012 columns(List<InlineResponse20012Columns> columns) {
    this.columns = columns;
    return this;
  }

  public InlineResponse20012 addColumnsItem(InlineResponse20012Columns columnsItem) {
    if (this.columns == null) {
      this.columns = new ArrayList<InlineResponse20012Columns>();
    }
    this.columns.add(columnsItem);
    return this;
  }

   /**
   * Table columns info
   * @return columns
  **/
  @Schema(description = "Table columns info")
  public List<InlineResponse20012Columns> getColumns() {
    return columns;
  }

  public void setColumns(List<InlineResponse20012Columns> columns) {
    this.columns = columns;
  }

  public InlineResponse20012 foreignKeys(List<InlineResponse20012ForeignKeys> foreignKeys) {
    this.foreignKeys = foreignKeys;
    return this;
  }

  public InlineResponse20012 addForeignKeysItem(InlineResponse20012ForeignKeys foreignKeysItem) {
    if (this.foreignKeys == null) {
      this.foreignKeys = new ArrayList<InlineResponse20012ForeignKeys>();
    }
    this.foreignKeys.add(foreignKeysItem);
    return this;
  }

   /**
   * Table list of foreign keys
   * @return foreignKeys
  **/
  @Schema(description = "Table list of foreign keys")
  public List<InlineResponse20012ForeignKeys> getForeignKeys() {
    return foreignKeys;
  }

  public void setForeignKeys(List<InlineResponse20012ForeignKeys> foreignKeys) {
    this.foreignKeys = foreignKeys;
  }

  public InlineResponse20012 indexes(List<InlineResponse20012ForeignKeys> indexes) {
    this.indexes = indexes;
    return this;
  }

  public InlineResponse20012 addIndexesItem(InlineResponse20012ForeignKeys indexesItem) {
    if (this.indexes == null) {
      this.indexes = new ArrayList<InlineResponse20012ForeignKeys>();
    }
    this.indexes.add(indexesItem);
    return this;
  }

   /**
   * Table list of indexes
   * @return indexes
  **/
  @Schema(description = "Table list of indexes")
  public List<InlineResponse20012ForeignKeys> getIndexes() {
    return indexes;
  }

  public void setIndexes(List<InlineResponse20012ForeignKeys> indexes) {
    this.indexes = indexes;
  }

  public InlineResponse20012 primaryKey(InlineResponse20012PrimaryKey primaryKey) {
    this.primaryKey = primaryKey;
    return this;
  }

   /**
   * Get primaryKey
   * @return primaryKey
  **/
  @Schema(description = "")
  public InlineResponse20012PrimaryKey getPrimaryKey() {
    return primaryKey;
  }

  public void setPrimaryKey(InlineResponse20012PrimaryKey primaryKey) {
    this.primaryKey = primaryKey;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20012 inlineResponse20012 = (InlineResponse20012) o;
    return Objects.equals(this.columns, inlineResponse20012.columns) &&
        Objects.equals(this.foreignKeys, inlineResponse20012.foreignKeys) &&
        Objects.equals(this.indexes, inlineResponse20012.indexes) &&
        Objects.equals(this.primaryKey, inlineResponse20012.primaryKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(columns, foreignKeys, indexes, primaryKey);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20012 {\n");
    
    sb.append("    columns: ").append(toIndentedString(columns)).append("\n");
    sb.append("    foreignKeys: ").append(toIndentedString(foreignKeys)).append("\n");
    sb.append("    indexes: ").append(toIndentedString(indexes)).append("\n");
    sb.append("    primaryKey: ").append(toIndentedString(primaryKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
