/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package at.mic.superset.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
/**
 * LogRestApiPut
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-06T17:36:10.263+01:00[Europe/Vienna]")
public class LogRestApiPut {
  @SerializedName("action")
  private String action = null;

  @SerializedName("dttm")
  private OffsetDateTime dttm = null;

  @SerializedName("json")
  private String json = null;

  @SerializedName("user")
  private Object user = null;

  public LogRestApiPut action(String action) {
    this.action = action;
    return this;
  }

   /**
   * Get action
   * @return action
  **/
  @Schema(description = "")
  public String getAction() {
    return action;
  }

  public void setAction(String action) {
    this.action = action;
  }

  public LogRestApiPut dttm(OffsetDateTime dttm) {
    this.dttm = dttm;
    return this;
  }

   /**
   * Get dttm
   * @return dttm
  **/
  @Schema(description = "")
  public OffsetDateTime getDttm() {
    return dttm;
  }

  public void setDttm(OffsetDateTime dttm) {
    this.dttm = dttm;
  }

  public LogRestApiPut json(String json) {
    this.json = json;
    return this;
  }

   /**
   * Get json
   * @return json
  **/
  @Schema(description = "")
  public String getJson() {
    return json;
  }

  public void setJson(String json) {
    this.json = json;
  }

  public LogRestApiPut user(Object user) {
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  @Schema(description = "")
  public Object getUser() {
    return user;
  }

  public void setUser(Object user) {
    this.user = user;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LogRestApiPut logRestApiPut = (LogRestApiPut) o;
    return Objects.equals(this.action, logRestApiPut.action) &&
        Objects.equals(this.dttm, logRestApiPut.dttm) &&
        Objects.equals(this.json, logRestApiPut.json) &&
        Objects.equals(this.user, logRestApiPut.user);
  }

  @Override
  public int hashCode() {
    return Objects.hash(action, dttm, json, user);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LogRestApiPut {\n");
    
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    dttm: ").append(toIndentedString(dttm)).append("\n");
    sb.append("    json: ").append(toIndentedString(json)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
