/*
 * Superset
 * Superset
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package at.mic.superset.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
/**
 * Meta12
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-11-06T17:36:10.263+01:00[Europe/Vienna]")
public class Meta12 {
  @SerializedName("changed_on")
  private OffsetDateTime changedOn = null;

  @SerializedName("column_name")
  private String columnName = null;

  @SerializedName("created_on")
  private OffsetDateTime createdOn = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("expression")
  private String expression = null;

  @SerializedName("filterable")
  private Boolean filterable = null;

  @SerializedName("groupby")
  private Boolean groupby = null;

  @SerializedName("id")
  private Integer id = null;

  @SerializedName("is_active")
  private Boolean isActive = null;

  @SerializedName("is_dttm")
  private Boolean isDttm = null;

  @SerializedName("python_date_format")
  private String pythonDateFormat = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("verbose_name")
  private String verboseName = null;

  public Meta12 changedOn(OffsetDateTime changedOn) {
    this.changedOn = changedOn;
    return this;
  }

   /**
   * Get changedOn
   * @return changedOn
  **/
  @Schema(description = "")
  public OffsetDateTime getChangedOn() {
    return changedOn;
  }

  public void setChangedOn(OffsetDateTime changedOn) {
    this.changedOn = changedOn;
  }

  public Meta12 columnName(String columnName) {
    this.columnName = columnName;
    return this;
  }

   /**
   * Get columnName
   * @return columnName
  **/
  @Schema(required = true, description = "")
  public String getColumnName() {
    return columnName;
  }

  public void setColumnName(String columnName) {
    this.columnName = columnName;
  }

  public Meta12 createdOn(OffsetDateTime createdOn) {
    this.createdOn = createdOn;
    return this;
  }

   /**
   * Get createdOn
   * @return createdOn
  **/
  @Schema(description = "")
  public OffsetDateTime getCreatedOn() {
    return createdOn;
  }

  public void setCreatedOn(OffsetDateTime createdOn) {
    this.createdOn = createdOn;
  }

  public Meta12 description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Meta12 expression(String expression) {
    this.expression = expression;
    return this;
  }

   /**
   * Get expression
   * @return expression
  **/
  @Schema(description = "")
  public String getExpression() {
    return expression;
  }

  public void setExpression(String expression) {
    this.expression = expression;
  }

  public Meta12 filterable(Boolean filterable) {
    this.filterable = filterable;
    return this;
  }

   /**
   * Get filterable
   * @return filterable
  **/
  @Schema(description = "")
  public Boolean isFilterable() {
    return filterable;
  }

  public void setFilterable(Boolean filterable) {
    this.filterable = filterable;
  }

  public Meta12 groupby(Boolean groupby) {
    this.groupby = groupby;
    return this;
  }

   /**
   * Get groupby
   * @return groupby
  **/
  @Schema(description = "")
  public Boolean isGroupby() {
    return groupby;
  }

  public void setGroupby(Boolean groupby) {
    this.groupby = groupby;
  }

  public Meta12 id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Meta12 isActive(Boolean isActive) {
    this.isActive = isActive;
    return this;
  }

   /**
   * Get isActive
   * @return isActive
  **/
  @Schema(description = "")
  public Boolean isIsActive() {
    return isActive;
  }

  public void setIsActive(Boolean isActive) {
    this.isActive = isActive;
  }

  public Meta12 isDttm(Boolean isDttm) {
    this.isDttm = isDttm;
    return this;
  }

   /**
   * Get isDttm
   * @return isDttm
  **/
  @Schema(description = "")
  public Boolean isIsDttm() {
    return isDttm;
  }

  public void setIsDttm(Boolean isDttm) {
    this.isDttm = isDttm;
  }

  public Meta12 pythonDateFormat(String pythonDateFormat) {
    this.pythonDateFormat = pythonDateFormat;
    return this;
  }

   /**
   * Get pythonDateFormat
   * @return pythonDateFormat
  **/
  @Schema(description = "")
  public String getPythonDateFormat() {
    return pythonDateFormat;
  }

  public void setPythonDateFormat(String pythonDateFormat) {
    this.pythonDateFormat = pythonDateFormat;
  }

  public Meta12 type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(description = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Meta12 verboseName(String verboseName) {
    this.verboseName = verboseName;
    return this;
  }

   /**
   * Get verboseName
   * @return verboseName
  **/
  @Schema(description = "")
  public String getVerboseName() {
    return verboseName;
  }

  public void setVerboseName(String verboseName) {
    this.verboseName = verboseName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Meta12 meta12 = (Meta12) o;
    return Objects.equals(this.changedOn, meta12.changedOn) &&
        Objects.equals(this.columnName, meta12.columnName) &&
        Objects.equals(this.createdOn, meta12.createdOn) &&
        Objects.equals(this.description, meta12.description) &&
        Objects.equals(this.expression, meta12.expression) &&
        Objects.equals(this.filterable, meta12.filterable) &&
        Objects.equals(this.groupby, meta12.groupby) &&
        Objects.equals(this.id, meta12.id) &&
        Objects.equals(this.isActive, meta12.isActive) &&
        Objects.equals(this.isDttm, meta12.isDttm) &&
        Objects.equals(this.pythonDateFormat, meta12.pythonDateFormat) &&
        Objects.equals(this.type, meta12.type) &&
        Objects.equals(this.verboseName, meta12.verboseName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(changedOn, columnName, createdOn, description, expression, filterable, groupby, id, isActive, isDttm, pythonDateFormat, type, verboseName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Meta12 {\n");
    
    sb.append("    changedOn: ").append(toIndentedString(changedOn)).append("\n");
    sb.append("    columnName: ").append(toIndentedString(columnName)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    expression: ").append(toIndentedString(expression)).append("\n");
    sb.append("    filterable: ").append(toIndentedString(filterable)).append("\n");
    sb.append("    groupby: ").append(toIndentedString(groupby)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    isActive: ").append(toIndentedString(isActive)).append("\n");
    sb.append("    isDttm: ").append(toIndentedString(isDttm)).append("\n");
    sb.append("    pythonDateFormat: ").append(toIndentedString(pythonDateFormat)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    verboseName: ").append(toIndentedString(verboseName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
